src/main/java/org/jsoup/select/Evaluator.java
src/test/java/org/jsoup/select/SelectorTest.java

This is a fix for #521 as discussed there.

Fix for classes with space (issue #521)

---

src/main/java/org/jsoup/select/Elements.java

Maybe it's just a personal preference, but if this collection is used a lot, maybe skipping the delegation can improve performance.

Refactor the Elements collection to extend instead of delegate

---

src/main/java/org/jsoup/helper/HttpConnection.java
src/main/java/org/jsoup/nodes/Attributes.java
src/main/java/org/jsoup/nodes/TextNode.java
src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java
src/main/java/org/jsoup/parser/Tokeniser.java
src/test/java/org/jsoup/helper/StringUtilTest.java
src/test/java/org/jsoup/nodes/EntitiesTest.java
src/test/java/org/jsoup/nodes/FormElementTest.java
src/test/java/org/jsoup/nodes/NodeTest.java
src/test/java/org/jsoup/parser/HtmlParserTest.java
src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java

Hi Jsoup team,
I was playing around with the the code and noticed that there are some linting/code inspection warnings. 
The changes should be all non-functional changes, just code style

Unused statements

---

src/main/java/org/jsoup/nodes/Node.java
src/main/java/org/jsoup/parser/Parser.java
src/test/java/org/jsoup/parser/HtmlParserTest.java

Here is a fix for performance issues for nodes with maaany children (https://github.com/jhy/jsoup/issues/504).

Fix for https://github.com/jhy/jsoup/issues/504

---

src/main/java/org/jsoup/helper/DataUtil.java
src/test/java/org/jsoup/helper/DataUtilTest.java

This is a pull request for issue #508 as posted by @BalusC.
A test is included.

Fix for UnsupportedCharsetException

---

pom.xml

to allow me to properly deploy to our working maven repository.

bump to 1.8.3-SNAPSHOT

---

src/main/java/org/jsoup/Connection.java
src/main/java/org/jsoup/Jsoup.java
src/main/java/org/jsoup/helper/HttpConnection.java

I implemented proxy support with minimal intrusion in the existing code.

Proxy support

---

src/main/java/org/jsoup/Connection.java
src/main/java/org/jsoup/helper/HttpConnection.java
src/test/java/org/jsoup/helper/HttpConnectionTest.java

Add Connection headers method(key-value pair)
It usedfull in many case

Add Connection.headers(map)

---

pom.xml

Maven plugins updated to latest versions.

Maven plugins updated to latest versions

---

src/main/java/org/jsoup/Connection.java
src/main/java/org/jsoup/helper/StringUtil.java
src/main/java/org/jsoup/nodes/Attribute.java
src/main/java/org/jsoup/nodes/Document.java
src/main/java/org/jsoup/nodes/Entities.java
src/main/java/org/jsoup/parser/Tag.java

I found some typos in the Javadocs

Fixed a few typos

---

src/main/java/org/jsoup/helper/HttpConnection.java

Fix for #872 
Set request body to null when doing a redirect

Set Request body to null when doing a redirecot

---

.travis.yml
CHANGES
src/main/java/org/jsoup/UncheckedIOException.java
src/main/java/org/jsoup/helper/DataUtil.java
src/main/java/org/jsoup/helper/HttpConnection.java
src/main/java/org/jsoup/helper/W3CDom.java
src/main/java/org/jsoup/internal/ConstrainableInputStream.java
src/main/java/org/jsoup/nodes/Entities.java
src/main/java/org/jsoup/parser/CharacterReader.java
src/main/java/org/jsoup/parser/HtmlTreeBuilder.java
src/main/java/org/jsoup/parser/Parser.java
src/main/java/org/jsoup/parser/TokeniserState.java
src/main/java/org/jsoup/parser/TreeBuilder.java
src/main/java/org/jsoup/parser/XmlTreeBuilder.java
src/main/java/org/jsoup/select/QueryParser.java
src/test/java/org/jsoup/helper/DataUtilTest.java
src/test/java/org/jsoup/helper/HttpConnectionTest.java
src/test/java/org/jsoup/integration/UrlConnectTest.java
src/test/java/org/jsoup/parser/CharacterReaderTest.java

Stream network loading

---

src/main/java/org/jsoup/nodes/Attribute.java

Check for null first, check for emptiness after trimming.

Make consistency checks consistent

---

src/main/java/org/jsoup/nodes/Entities.java

fixed issue #916 InputStream not closed in class org.jsoup.nodes.Entities.
use jdk7 try-with-resources to close "BufferReader input".

fixed issue #916

---

src/main/java/org/jsoup/nodes/Node.java

The same logic is implemented in setParentNode(Node parentNode).

Duplicated Logic in Called Method

---

src/main/java/org/jsoup/nodes/Element.java
src/test/java/org/jsoup/nodes/ElementTest.java

Removes redundant class attribute after removing last class from element.

removing last class should remove class attribute

---

CHANGES
src/main/java/org/jsoup/helper/HttpConnection.java

Deflate encoding support

---

pom.xml
src/main/java/org/jsoup/parser/TokenQueue.java
src/test/java/org/jsoup/parser/TokenQueueTest.java

Tests and resolution added for the issue (#987) in org.jsoup.parser package

Adding support for nested quotes in attribute selection

---

src/main/java/org/jsoup/select/Selector.java

fix typo in Selector.java

---

src/main/java/org/jsoup/helper/DataUtil.java
src/main/java/org/jsoup/helper/HttpConnection.java
src/main/java/org/jsoup/parser/HtmlTreeBuilder.java
src/main/java/org/jsoup/safety/Cleaner.java
src/main/java/org/jsoup/select/Evaluator.java
src/test/java/org/jsoup/MultiLocaleRule.java
src/test/java/org/jsoup/TextUtil.java
src/test/java/org/jsoup/nodes/NodeTest.java
src/test/java/org/jsoup/parser/AttributeParseTest.java
src/test/java/org/jsoup/parser/TokeniserTest.java
src/test/java/org/jsoup/select/ElementsTest.java
src/test/java/org/jsoup/select/TraversorTest.java

Code improvements

---

.travis.yml

Using https://github.com/DanySK/Gravis-CI

Fix Travis CI JDK issues

---

src/test/java/org/jsoup/integration/ConnectIT.java
src/test/java/org/jsoup/integration/ConnectTest.java
src/test/java/org/jsoup/integration/ParseTest.java
src/test/java/org/jsoup/integration/UrlConnectTest.java
src/test/java/org/jsoup/integration/servlets/Deflateservlet.java
src/test/java/org/jsoup/integration/servlets/FileServlet.java
src/test/java/org/jsoup/integration/servlets/HelloServlet.java
src/test/java/org/jsoup/integration/servlets/InterruptedServlet.java
src/test/java/org/jsoup/integration/servlets/RedirectServlet.java
src/test/java/org/jsoup/integration/servlets/SlowRider.java
src/test/java/org/jsoup/internal/StringUtilTest.java
src/test/java/org/jsoup/nodes/AttributeTest.java
src/test/java/org/jsoup/nodes/DocumentTest.java
src/test/java/org/jsoup/nodes/ElementTest.java
src/test/java/org/jsoup/nodes/EntitiesTest.java
src/test/java/org/jsoup/nodes/FormElementTest.java
src/test/java/org/jsoup/nodes/NodeTest.java
src/test/java/org/jsoup/nodes/TextNodeTest.java
src/test/java/org/jsoup/parser/AttributeParseTest.java
src/test/java/org/jsoup/parser/CharacterReaderTest.java
src/test/java/org/jsoup/parser/HtmlParserTest.java
src/test/java/org/jsoup/parser/ParserSettingsTest.java
src/test/java/org/jsoup/parser/TokenQueueTest.java
src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java
src/test/java/org/jsoup/select/ElementsTest.java

Assertions improved and not thrown exception declarations removed.

Tests cleanup

---

pom.xml

As suggested by @PascalSchumacher (https://github.com/jhy/jsoup/commit/8e432a5f5fde4694834ce23c5ac1503ce8d381bc#r37660819).

JUnit 5 dependency aggregator

---

.github/workflows/test-java-versions.yml

This makes use of the new GitHub CI Actions to test against all Java versions on the major OSes.
Signed-off-by: Carl Dea <carl.dea@gmail.com>

Test on Java versions on Linux, Windows and MacOS.

---

.gitignore

(Eclipse's default output folder)

Add bin/ to .gitignore

---

src/main/java/org/jsoup/internal/StringUtil.java

Use ThreadLocal stack to store StringBuilder instance cache to avoid thread contention introduced by synchronized
Our application which utilizes multithreads to parse html documents experienced performance degradation after updating from jsoup-1.10.x to recent version. Thread dump shows threads stuck at StringBuilder.borrowBuilder / releaseBuilder so the situation is very similar to #1352. It seems synchronized blocks in borrowBuilder / releaseBuilder is introduced in https://github.com/jhy/jsoup/commit/c8c05694da5489221c27e45a5e49d0f5fcb41863.
I conducted a microbenchmark of the improvement, which shows ~10x reduction in multithreaded StringBuilder.borrowBuilder / releaseBuilder operations.
https://github.com/morokosi/jsoup/pull/1

improve StringBuilder cache performance under high concurrency

---

CHANGES
README.md
pom.xml
src/main/java/org/jsoup/Jsoup.java
src/main/java/org/jsoup/safety/Cleaner.java
src/main/java/org/jsoup/safety/Safelist.java
src/main/java/org/jsoup/safety/Whitelist.java
src/main/java/org/jsoup/safety/package-info.java
src/main/javadoc/overview.html
src/test/java/org/jsoup/parser/HtmlParserTest.java
src/test/java/org/jsoup/safety/CleanerTest.java
src/test/java/org/jsoup/safety/CompatibilityTests.java

And introduced a (deprecated) compatibility shim.
Tested with japicmp binary and source compatibility report, and checked binary compat with some test utilities (local testing).
Many thanks to @drei01 (#1408), @nkiesel (#1423) and others for highlighting the issue and for PRs which this commit refines.

Corrected uses of Whitelist to Safelist

---

.github/workflows/build.yml

Java 16 release version CI build

---

src/main/java/org/jsoup/parser/HtmlTreeBuilder.java
src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java
src/test/java/org/jsoup/parser/HtmlTreeBuilderStateTest.java

I solved the example mentioned in #845 by update formatting elements recursively since I also not clearly understand the TODOs marked in [codes](https://github.com/jhy/jsoup/blob/78e14c4b7bd13baef6f153ecbcc91e21d2f929a3/src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java#L825) by [adoption agency algorithm](https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm).
I tested some cases trying to avoid side effects but still not sure and hope get your code reviews. 
Glad to work more on this issue.

Complete adoption agency algorithm

---

src/main/java/org/jsoup/select/QueryParser.java
src/test/java/org/jsoup/select/QueryParserTest.java

Fix issue #1425

---

.github/dependabot.yml

Dependabot ignore names fixed

---

.github/workflows/build.yml
.github/workflows/codeql.yml

`setup-java` supports caching now :+1::
https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

New GH Actions caching option

---

.github/workflows/build.yml

JDK 17 CI build

---

src/main/java/org/jsoup/select/Collector.java

Convert the private `Accumulator` class in `Collector` to a lambda expression.

Convert Accumulator to a lambda.

---

src/test/java/org/jsoup/parser/CharacterReaderTest.java

Hi! Here are some additions for `CharacterReaderTest` that test invalid conditions and uncovered branches.

Add new tests for CharacterReader

---

.github/workflows/build.yml
.github/workflows/codeql.yml

Updates the JDK and Action versions

Update GitHub Actions

---

src/main/java/org/jsoup/nodes/FormElement.java
src/test/java/org/jsoup/nodes/FormElementTest.java

This test should pass when fix issue #2009

formData retrieves "input type=image" incorrectly

---

.github/workflows/build.yml
.github/workflows/cifuzz.yml
.github/workflows/codeql.yml

Adds a CI build for Java 21 (LTS) and some Action updates.

Java 21 CI build

---

pom.xml
src/main/java/org/jsoup/select/CombiningEvaluator.java
src/test/java/org/jsoup/nodes/BuildEntities.java

Use Java 8's `Comparator` factory methods.

Use Comparator factory methods

---

.github/workflows/build.yml
pom.xml

For JDK 8+ support, incl on ARM

Use zulu vs temurin

---

.github/workflows/build.yml
.github/workflows/codeql.yml

To migrate from NodeJS 16 -> 20

Use setup-java@v4

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/codeql.yml

- Enable dependabot for github-actions
- Build for any branch push
- codeql for any branch push; update to v3; remove schedule

Updating workflows

---

src/main/java/org/jsoup/helper/CookieUtil.java
src/main/java/org/jsoup/parser/CharacterReader.java
src/main/java/org/jsoup/parser/TokenQueue.java
src/test/java/org/jsoup/parser/TokenQueueTest.java
src/test/java/org/jsoup/select/QueryParserTest.java

Removed redundancies between the classes, and simplified implementation.
[WIP] still need to review TokenQueue, see what else we can safely deprecate or dedupe
@cketti in #2297 I mentioned I would refactor TokenQueue and CharacterReader - this is a first pass. FYI in case you are doing other work in there.

Token queue refactor

---

src/main/java/org/jsoup/internal/StringUtil.java
src/main/java/org/jsoup/parser/HtmlTreeBuilder.java
src/main/java/org/jsoup/parser/Token.java
src/main/java/org/jsoup/parser/TokenData.java
src/main/java/org/jsoup/parser/Tokeniser.java
src/main/java/org/jsoup/parser/TokeniserState.java
src/main/java/org/jsoup/parser/TreeBuilder.java
src/main/java/org/jsoup/parser/XmlTreeBuilder.java

Goal of minimizing new StringBuilders on each new parse, and simplifying the code.
Gives a decent GC reduction

Use TokenData to simplify String + StringBuilder use
