src/test/java/org/jsoup/TextUtil.java, src/test/java/org/jsoup/helper/W3CDomTest.java
The W3CDomTest simpleConversion test fails on windows since it is using "\n" as the
line ending. Using a platform independent line ending i.e. \r\n on windows
or \n on unix, fixes it.
=> Use platform independent line endings in W3CDomTest.

src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/test/java/org/jsoup/nodes/DocumentTest.java, src/test/java/org/jsoup/parser/HtmlParserTest.java
update the ```InHeadNoscript``` parser to insert invalid tokens as character nodes rather than prematurely ending the head node.
Fixes https://github.com/jhy/jsoup/issues/539
=> store invalid head/noscript tokens as character tokens

src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/examples/HtmlToPlainText.java, src/main/java/org/jsoup/helper/W3CDom.java, src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Entities.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/parser/Tag.java, src/main/java/org/jsoup/safety/Cleaner.java, src/main/java/org/jsoup/safety/Whitelist.java, src/main/java/org/jsoup/select/Elements.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/NodeTraversor.java, src/main/java/org/jsoup/select/NodeVisitor.java, src/main/java/org/jsoup/select/Selector.java
Building Jsoup with JDK8 causes a long list of JavaDoc *warnings (5)* and *errors (86)*. Maven reports a failed build for Javadoc, however it's still working and correct. The reason is, that JDK8 introduced stricter rules for html formating.
This pull request fixes *all* of these errors / warnings so a clean and successful build is possible with JDK8. The documentation's formating itself is kept.
=> Fixed JavaDoc errors and warnings for JDK8 with stricter doc rules

src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/HttpConnection.java
Updates to Connection and Request interfaces and HttpConnection implementation.   This allows for the specification of the charset used for application/x-www-form-urlencoded post data character set, which is needed for more robust support.   The implementation was done by adding a postDataCharset method to the request object with the default value still maintaining the DataUtils.defaultCharset.   This implementation should have minimum effect on current applications as the default is still UTF-8 but allows the setting of ISO-8859-1 which appears frequently in use on the web.  I've also added the charset= parameter to the header setting to allow the server to be aware of the charset used, although I've found this isn't always honored...
Fixes issue #155
=> Update to allow for specification of form post data charset.

CHANGES, src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/XmlDeclaration.java, src/test/java/org/jsoup/nodes/DocumentTest.java
This pull request attends the todo-comment according the update of documents meta charset tag.
If the charset is changed, the charset meta-tag of the document is slected and updated (if existing).
An improvement could be an overload `charset()` method, where the caller can choose if the meta tag will be updated too.
A test is included.
=> Update meta charset

src/main/java/org/jsoup/parser/TokeniserState.java, src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java
We use Hibernate Validator (HV) and the @SafeHtlm annotation to validate input from users. During a security review we discovered that an unsafe XSS vector slipped by the validator. During debugging HV we discovered that the source of the problem was related to how Jsoup handled tags without a closing > when reaching EOF.
[Code reference to SafeHtmlValidator in HV](https://github.com/hibernate/hibernate-validator/blob/dfa65141d63cbfbb33f79522f6ba40a6d2b29b5c/engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/SafeHtmlValidator.java#L75)
=> Keep tag that have not been closed by > before reaching EOF.

src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/BooleanAttribute.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/parser/AttributeParseTest.java, src/test/java/org/jsoup/parser/HtmlParserTest.java
* Adds BooleanAttribute that writes out itself without a value
* Adds API in Element for setting boolean attributes
* Update parser to distinguish between no value and empty value
=> Add custom boolean attribute support #503

src/main/java/org/jsoup/select/StructuralEvaluator.java, src/test/java/org/jsoup/select/SelectorTest.java
The "parent" Evaluator has a kind of "off by one" error - it does not match, when the expression requires matching the provided root element.
It seems to me, that this bugfix also solves  #417 and #535.
=> Fix "Parent" Evaluator ignores "root" argument for matches.

src/main/java/org/jsoup/select/Evaluator.java, src/test/java/org/jsoup/parser/HtmlParserTest.java
This small change makes it possible to use single quotes in queries like this one: 
```java
Document doc = Jsoup.parse(responseContent());
Elements main = doc.select("a[data-file='123']");
```
Before this fix, you could only use double quotes, even if single quotes were actually used in HTML.
=> #650 Cannot use single quotes in selectors

src/main/java/org/jsoup/helper/HttpConnection.java
Currently the request method is changed to GET and the data is dropped when the request is redirected. 
However, according to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection & https://tools.ietf.org/html/rfc7231#section-6.4.7, 307 redirect should preserve the original method and the data.
This patch corrects this problem.
=> 307 redirect should preserve request method & data

src/main/java/org/jsoup/helper/W3CDom.java, src/main/java/org/jsoup/select/NodeTraversor.java, src/test/java/org/jsoup/helper/W3CDomTest.java, src/test/resources/htmltests/cover.xhtml
Added code to parse the namespace, if exists, and pass it to the NodeTraversor constructor and traverse() methods.  createElementNS() is used instead of createElement() when creating nodes in the W3C Dom document.
Added a unit test to validate that getNamespaceURI() and getLocalName() calls work on elements of the created W3C Dom document.
Added a sample XHTML file.
=> Fix for bug 671: namespace is included in W3CDom.fromJsoup

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
I have been seeing the following error parsing a huffingtonpost site:
```
Exception in thread "main" org.jsoup.select.Selector$SelectorParseException: Could not parse query 'fb:comments': unexpected token at ':comments'
at org.jsoup.select.QueryParser.findElements(QueryParser.java:196)
at org.jsoup.select.QueryParser.parse(QueryParser.java:65)
at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
at org.jsoup.select.QueryParser.combinator(QueryParser.java:81)
at org.jsoup.select.QueryParser.parse(QueryParser.java:51)
at org.jsoup.select.QueryParser.parse(QueryParser.java:39)
at org.jsoup.select.Selector.<init>(Selector.java:83)
at org.jsoup.select.Selector.select(Selector.java:105)
at org.jsoup.nodes.Element.select(Element.java:273)
at …
```
=> Tag namespaces cause cssSelector() to fail

src/main/java/org/jsoup/parser/TokenQueue.java, src/main/java/org/jsoup/select/CombiningEvaluator.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/QueryParser.java, src/main/java/org/jsoup/select/Selector.java, src/test/java/org/jsoup/select/SelectorTest.java
By using the "endsWith", it's possible an element named: "ns:foo:bar" with selector "*|bar" or "*|foo:bar", which shouldn't be valid (https://www.w3.org/TR/REC-xml-names/#ns-decl), but it's also fairly flexible/error-tolerant
=> Add wildcard-namespace selector support '*|' Issue #723

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
this method is perf sensitive (CPU and memoryallocations)
This replaces the regexp split with a custom implementation that do not
allocate unneeded memory.
With this patch a simple test calling Element#select in a loop for
several selector went from 3Gb allocated to 10Mb.
GC times were reduced.
Fixes #752
=> optimize Element#hasClass

src/main/java/org/jsoup/nodes/Attributes.java, src/test/java/org/jsoup/nodes/AttributesTest.java
It allocates a lot of memory during the parsing through
ParseSettings#normalizeAttributes.
this new implementation just wrap the LinkedHashMap values iterator in a
read-only iterator.
Iterating 1000 times over an internal html file (~800Kb) was allocating
970Mb, with this optimization it's now 350Mb
Fixes #754
=> Optimize Attribute#iterator

.travis.yml
Extends the CI builds to following JDK's:
- OpenJDK 6
- OpenJDK 7
- Oracle JDK 7
- Oracle JDK 8
=> CI: Building against JDK6 - 8

pom.xml
Workaround for #772: Downgrade **maven-bundle-plugin** to **v2.x**. This enables JDK6 builds.
=> Workaround for #772: Downgrade maven-bundle-plugin to v2.x.

src/main/java/org/jsoup/helper/DataUtil.java, src/test/java/org/jsoup/helper/DataUtilTest.java
Current state:
When attempting to retrieve the charset only the first meta element with content type information will be looked at. No further meta elements are considered even when the first one doesn't contain a charset parameter. See `DataUtilTest.secondMetaElementWithContentTypeContainsCharsetParameter()`.
With this fix:
All meta elements are looked at until a charset is found, i.e. the first viable one is used.
Fixes #834
=> Try harder to get charset from meta elements

src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/Normalizer.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/parser/ParseSettings.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/safety/Whitelist.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/QueryParser.java, src/test/java/org/jsoup/MultiLocaleRule.java, src/test/java/org/jsoup/helper/HttpConnectionTest.java, src/test/java/org/jsoup/parser/ParserSettingsTest.java, src/test/java/org/jsoup/parser/TagTest.java, src/test/java/org/jsoup/safety/CleanerTest.java, src/test/java/org/jsoup/select/SelectorTest.java
`String.toLowerCase()` uses the default locale for the case conversion. This can lead to undesired results when using the Turkish locale (see the blog post linked in issue #256).
This pull request adds some tests to make sure jsoup's behavior is independent of the default locale. `MultiLocaleRule` runs every test annotated with `@MultiLocaleTest` twice. Once with `Locale.ENGLISH` as the default locale and once with Turkish as the default value.
This does not fix content matching issues with non-ASCII data, e.g. the one described in issue #474. However, it now consistently fails independent of the default locale.
Fixes #256
=> Don't use default locale when lowercasing

src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/Node.java, src/test/java/org/jsoup/nodes/NodeTest.java
This changes `Node#attr(String, String)` to compare attribute keys case-insensitive to see if there is an existing attribute that needs to be replaced. The order of attributes is retained when the case of the new attribute key and the existing attribute key match. If not the existing attribute is removed and the new one is added at the end. This is mostly due to the limitations of `LinkedHashMap`.
Fixes #815
=> Case-insensitive attribute setter

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
appendTo method appends the element to a given parent element and returns itself, instead of the parent. See jQuery's appendTo method for further information.
As an example, use the code below;
```
element.appendTo(parentElement).attr('class', 'text-danger').text('Alert!!');
```
Instead of the code below;
```
element.attr('class', 'text-danger').text('Alert!!');
parentElement.appendChild(element);
```
=> Add appendTo method to Element.

src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/test/java/org/jsoup/parser/HtmlParserTest.java
This PR will fix the parser issue introduced by b934c5d and commented by @Tunous.
```
input: "<r><X>A</X><y>B</y></r>"
expected: "<r> <x> A </x> <y> B </y> </r>"
actual: "<r> <x> A <y> B </y> </x> </r>"
```
We got the same with a mixed-case `<noScript>` element in some of our html input.
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<STYLE type="text/css">
body { padding:10px; }
</STYLE>
</head>
<body>
<noScript>no Javascript enabled</noScript>
<h1>Headline1</h1>
<h2>Headline 2</h2>
</body>
</html>
```
=> [fix] parsing of mixed-case tags after b934c5d

src/main/java/org/jsoup/nodes/Node.java
patch about  issue #836 addChildren is quadratic
when add many children, the origin implementation will move childNodes array per loop.(method add(index, obj)),
a performance improvement was made using addAll(index, objs).there are three steps:
1. reparent all the children
2. use addAll(index, objs) to insert children
3. reset sibling index
it is very similar with method addChildren(Node... children).
=> patch about issue #836 addChildren is quadratic

src/test/java/org/jsoup/parser/TokenQueueTest.java
Since pos is a class attribute, calling consumeToIgnoreCase() on the same queue will return different Strings. If this is the intended behavior than this test preserves that. If not the second assert should be changed to assertEquals("<textarea>one < two ", data); . Nevertheless that would cause the test to fail based on current implementation. This missing behavior preservation was detected by running mutation testing analysis.
=> Missing Test Case to preserve consumeToIgnoreCase() behavior

src/test/java/org/jsoup/nodes/ElementTest.java
The method that checks if an element has a class is never tested for a class name that ends with a whitespace. The implemented functionality is correct however if the "if (i - start == wantLen && classAttr.regionMatches(true, start, className, 0, wantLen)) {" check is removed, no tests catch this. The missing test case was discovered through mutation testing analysis.
=> Missing Test Case for whitespace class name

src/test/java/org/jsoup/helper/W3CDomTest.java
By running mutation testing analysis I discovered that when a jsoup document is being converted into a W3C document the location parsing is never tested. To this end we propose another test case.
=> Missing Test Case for location conversion

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
Add `Element#getWholeText()` to get raw text in the element easily.
=> Add Element#getWholeText()

pom.xml
I noticed that the examples from the main source tree appear in the release artifacts. Assuming that this is not intended, I have setup a patch that prevents the classes from the org.jsoup.examples package from being included in the *.jar and *-sources.jar artifacts.
I think an alternative approach would be to move the examples to a separate source tree (or different project). What do you think?
=> Exclude examples from artifacts

src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/Token.java
It would be extremely useful to be able to extend the HTML parser. For example, in our case we want to keep track of the line numbers for each tag in the original HTML output. Rather than adding every possible edge case to the standard HtmlTreeBuilder, it would be nice if people would be allowed to create their own subclasses.
Jsoup is currently a bit consistent in terms of allowing this. XmlTreeBuilder does allow subclasses, but HtmlTreeBuilder has a package-private constructor that prevents subclasses. This obviously has downsides in terms of maintainability from your side: allowing user-defined extensions would increase the chance that those subclasses will break in case of future changes to the HtmlTreeBuilder API. However, from looking at some of the issues it appears that obtaining …
=> Allow HtmlTreeBuilder subclasses

src/main/java/org/jsoup/parser/Tokeniser.java, src/test/java/org/jsoup/parser/TokeniserTest.java
=> Parse invalid unicode escapes as Windows-1252 instead [Fixes #1034]

CHANGES, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/HttpConnection.java
This way we can still control the SSL handshake, without disabling certification validation altogether.
=> Accept a custom SSL socket factory

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
Currently, element can only get the nearest sibling before or after, but in my actual work, I ofter need to get **all** of it's siblings before or after. So I add this two methods, it's really helpful and convenient.
Hope to merge
=> Add methods to get all the element siblings before or after current element

.travis.yml
This adds  Oracle JDK10  and JDK11 CI build. This PR supersedes #1078 (branch deleted accidentally)
@jhy Does it make sense to add an OpenJDKs build too?
=>  Oracle JDK10 and JDK11 build added to Travis

src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/main/java/org/jsoup/parser/Parser.java
Based on ["Arrays of Wisdom of the Ancients"](https://shipilev.net/blog/2016/arrays-wisdom-ancients/) and  similar issues submitted in other projects like this one ["Avoid calling list.toArray(new X[list.size()]) for performance"](https://github.com/h2database/h2database/issues/311), I would recommend jsoup also reuse this optimization since it's a library used so widely.
=> optimize toArray via change length to 0 directly - Avoid calling list.toArray(new X[list.size()])

src/main/java/org/jsoup/parser/Tag.java
This adds `center` to the list of block tags.
This fixes `Element.text()` for elements that have `<center>`s. For example:
```java
Jsoup.parse("<center>hello</center><center>goodbye</center>").body().text()
```
Before this change, this code evaluates to `hellogoodbye`. With this change, it evaluates to `hello goodbye`.
I tested the change with `mvn test` and it looks like everything is still happy. I also checked the call hierarchy of `Tag.isBlock()` and it looks like this change should be innocuous. Fingers crossed.
=> Add "center" to list of block tags

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
Fix for issue #1201 .
When you shallow clone an element you would expect that modifying the attributes of the clone would have no effect on the original element but this is not the case. shallowClone() reuses the same Attributes object from the original element. We should be cloning the Attributes instead.
=> Clone attributes in shallowClone()

src/main/java/org/jsoup/nodes/Element.java
Element.getElementsMatchingOwnText(String regex) did not specify it only matches on "own text" making docs a bit confusing when skimming through.
=> Fix inconsistent javadoc for Element.getElementsMatchingOwnText(String regex)

.travis.yml
OpenJDK 12 CI build added. OracleJDK is no longer possible due to license changes.
=> JDK 12 CI build

pom.xml
Fix for the JavaDoc generation failure on JDK11 and JDK12 (OpenJDK bug [**JDK-8212233**](https://bugs.openjdk.java.net/browse/JDK-8212233)).
In addition, update to _Maven JavaDoc Plugin v3.1.0_ and the new `doclint` option, introduced with v3.0.0.
=> Jdk11 / Jdk12 JavaDoc generation fix

src/main/java/org/jsoup/parser/CharacterReader.java, src/main/java/org/jsoup/parser/Tokeniser.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/test/java/org/jsoup/parser/CharacterReaderTest.java, src/test/java/org/jsoup/parser/TokeniserTest.java
These changes are fixes for issues I've found while working on #1242. The original issue I've opened #1242 for is solved now, but I think it's worthwhile to merge these other minor fixes.
=> Fix edge cases with delimiters being near a buffer boundary.

src/main/java/org/jsoup/internal/Normalizer.java, src/main/java/org/jsoup/select/Evaluator.java, src/test/java/org/jsoup/select/SelectorTest.java
The general idea is that the value of the `startswith`-selector may contain spaces if it is inside quotes, in which case we don't trim the value.
=> fix for bug #1279

src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
There is no easy way in the Element to find out a number of children available via the method child(int). The method childNodeSize() acts on list of all children while child(int) acts on the filtered list of the children. This trivial patch adds new method childrenCount() that is complementary to child(int) as it works on the same filtered list. A unit test is provided.
My observation: https://stackoverflow.com/questions/59547574/jsoup-how-to-find-out-elements-size
Thank you for this wonderful library and for consideration of merging this proposal.
=> Added new method childrenCount complementary to child(int)

src/main/java/org/jsoup/helper/HttpConnection.java
String#replace does not use a regular expression for the replacement on Java 9+ and is therefore faster.
=> Use String#replace instead of String#replaceAll where possible.

src/main/java/org/jsoup/parser/TokenQueue.java
TokenQueue#consume returns a primitive character, so boxing seems unnecessary.
=> Avoid unnecessary boxing of char in TokenQueue#chompBalanced.

src/main/java/org/jsoup/helper/DataUtil.java, src/test/java/org/jsoup/helper/DataUtilTest.java
It is not documented explicitly, but `CharBuffer.array()` "Returns the char array that backs this buffer", so the buffer may have excess space at the end that was not used for the input.
(See also the explanation why https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6442955 is not a bug: 
> The Charset Buffer API is optimized for efficiency, not convenience. Buffer copies are avoided, but this means some buffers have extra elements between their limit and their capacity.
)
In a recent change to DataUtil the `array()` was passed without restricting its use to the length of `limit()`, hence adding NULL characters at the end.
Fixed by passing the value of `limit()` to the `CharArrayReader` that is actually reading from the `array()`.
=> Limit reading CharBuffer.array() to CharBuffer.limit() to avoid additional NULL characters at the end of some inputs

src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/nodes/Document.java
Also solves thread contention in the constructor of OutputSettings.
Fixes #1454
=> Use constants for the standard charsets (#1454)

src/main/java/org/jsoup/select/Elements.java, src/test/java/org/jsoup/select/ElementsTest.java
the `Elements.forms()` method used to return FormElement-s that are directly in the Elements collection. This behaviour was broken since a657ae0240b875a703a1e4909d56ad59997d362d. See https://github.com/jhy/jsoup/issues/1384
I wrote the fix accordingly to what's written in the javadocs of the methods involved:
* `comments`, `textNodes` and `dataNodes` says they return direct child nodes. I specialized the private `nodesOfType` method to handle child node lookup only (and renamed it `childNodesOfType`)
* `forms()` doc says it returns the forms elements present in the selected elements, not child nodes. I removed the use of `nodesOfType` and put back the previous code.
=> Fix regression on Elements.forms()

.github/workflows/build.yml, pom.xml
Verified that the GitHub CI Action now succeeds on JDK 16-ea, with the fixes in japacmp 0.15.2.
https://github.com/siom79/japicmp/issues/275
https://github.com/siom79/japicmp/issues/279
=> Update japicmp, and enable JDK 16-ea CI builds

pom.xml, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/HttpStatusException.java, src/main/java/org/jsoup/Jsoup.java, src/main/java/org/jsoup/helper/CookieUtil.java, src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/StringUtil.java, src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/FormElement.java, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/ParseErrorList.java, src/main/java/org/jsoup/parser/ParseSettings.java, src/main/java/org/jsoup/parser/Parser.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/main/java/org/jsoup/parser/XmlTreeBuilder.java, src/test/java/org/jsoup/helper/HttpConnectionTest.java, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/SessionIT.java, src/test/java/org/jsoup/integration/SessionTest.java, src/test/java/org/jsoup/integration/TestServer.java, src/test/java/org/jsoup/integration/servlets/CookieServlet.java, src/test/java/org/jsoup/integration/servlets/EchoServlet.java, src/test/java/org/jsoup/integration/servlets/FileServlet.java, src/test/java/org/jsoup/integration/servlets/SlowRider.java, src/test/java/org/jsoup/nodes/DocumentTest.java, src/test/java/org/jsoup/nodes/FormElementTest.java
This extends the Connection implementation to support (optional) sessions, which allow request defaults (timeout, proxy, etc) to be set once and then applied to all requests within that session. 
Cookies are re-implemented to correctly support path and domain filtering when used within a session. A default in-memory cookie store is used for the session, or a custom implementation (perhaps disk-persistent, or pre-set) can be used instead.
Forms submitted using the `FormElement#submit()` use the same session that was used to fetch the document and so pass cookies and other defaults appropriately.
The session is multi-thread safe and can execute multiple requests concurrently. If the user accidently tries to execute the same request object across multiple threads (vs calling …
=> Adds easy request session-state and corrects cookie domain and path rules

src/main/java/org/jsoup/internal/StringUtil.java, src/test/java/org/jsoup/internal/StringUtilTest.java
Some webpages may have abnormal URLs i.e. there are more ".." segments in a relative path reference than there are hierarchical levels in the base URL. Currently such extra segments are not resolved and remain as is. However, the extra segments should be removed according to 
https://tools.ietf.org/html/rfc3986#section-5.4.2 .
This will fix relative URL resolution and add test cases from rfc3986.
=> resolve abnormal urls in compliance with rfc3986

src/main/java/org/jsoup/parser/TokenQueue.java, src/main/java/org/jsoup/select/Selector.java, src/test/java/org/jsoup/parser/TokenQueueTest.java
For `Pattern.quote()`, it turns a regex into a raw value, which if matched directly as an argument to `:match()` could cause an error like the one below mentioned in #986 due to lack of deliberate escaping.
```java
final Document doc = Jsoup.parse("<div>1) foo</div>");
System.out.println(doc.select("div:matches(" + Pattern.quote("1)") + ")"));
```
Therefore supports detection of the `\Q` and `\E` that  `Pattern.quote()` generates when parsing.
=> Support for match with quoted pattern

.github/dependabot.yml
Ignores major updates of Jetty (#1574).
=> Dependabot: Ignore major Jetty updates

CHANGES, pom.xml, src/main/java/org/jsoup/Jsoup.java, src/main/java/org/jsoup/helper/W3CDom.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/NodeUtils.java, src/test/java/org/jsoup/TextUtil.java, src/test/java/org/jsoup/helper/W3CDomTest.java, src/test/java/org/jsoup/select/XpathTest.java
This is a first draft of adding native XPath support to jsoup. It uses the Java provided XPath parser & evaluator, so should fully support all valid XPath expressions.
As a starting point, I've added the method:
```java
Elements el.selectXpath(String expression)
```
For example:
```java
String html = "<body><div><p>One</div><div><p>Two</div><div>Three</div>";
Document doc = Jsoup.parse(html);
Elements els = doc.selectXpath("//div/p");
assertEquals(2, els.size());
assertEquals("One", els.get(0).text());
assertEquals("Two", els.get(1).text());
```
I'm planning on bringing this in as a *beta* feature in the next release (1.14.3 -- I'll add a few more tests first) and then hopefully finalizing it in a release shortly following that. I'm looking for all feedback on how to make this feature …
=> Native XPath support in jsoup

CHANGES, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/main/java/org/jsoup/parser/Tag.java, src/test/java/org/jsoup/parser/HtmlParserTest.java, src/test/java/org/jsoup/parser/HtmlTreeBuilderStateTest.java, src/test/java/org/jsoup/parser/HtmlTreeBuilderTest.java
This implements the HTML5 parser spec for `<template>` tags.
Note that as jsoup is a parser and does not run scripts, and for unsurprising selector support, it does not wrap the contents of the template children in a Document fragment object. Per #1634
We could choose to add a TemplateElement class with extra functionality around cloning the children etc. Very open to suggestions here!
Fixes #1634
Fixes #1630
Fixes #1409
Fixes #1315
=> Added full parser support for template tags

src/main/java/org/jsoup/parser/XmlTreeBuilder.java
so they can be re-used in jsoup-json's JsonTreeBuilder without copy-paste
https://github.com/magicprinc/jsoup.json
=> Change insertNode and popStackToClose from private to protected

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which jsoup already runs.
CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above).
=> Add CIFuzz integration to GitHub Actions

.github/workflows/build.yml
Removes deprecated jdk 16 from github actions.
=> [actions] Remove jdk 16 from github actions as end of life

src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/test/java/org/jsoup/helper/DataUtilTest.java, src/test/java/org/jsoup/parser/ParserTest.java, src/test/java/org/jsoup/parser/TokeniserTest.java
retains support or older usage of andriod as indicated in the source file.  Test end didn't matter in that regard as seen by other code.
=> [modernize] Use already compiled charsets instead of recompiling them

README.md, pom.xml, src/main/java/org/jsoup/helper/Consumer.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java, src/test/java/org/jsoup/nodes/ElementTest.java
* Use the `Consumer` interface introduced in Java 8, as it can be backported for older versions of Android via [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
=> Use Java 8's Consumer interface.

src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/test/java/org/jsoup/parser/HtmlParserTest.java
This is an attempt to handle deduplication of attributes in form-elements and should fix #1949
=> Add testcase and fix for attributes deduplication in form and empty elements

src/main/java/org/jsoup/select/Collector.java
Remove unnecessary override in `FirstFinder`.
=> Remove unnecessary override.

CHANGES, src/main/java/org/jsoup/nodes/Document.java, src/test/java/org/jsoup/nodes/EntitiesTest.java
Cloning OutputSettings leads to NPE during escaping
Code example:
```
private static final Document.OutputSettings DEFAULT = new Document.OutputSettings();
@Test
public void test() {
Entities.escape("text", DEFAULT.clone());
Entities.escape("text", DEFAULT.clone());
}
```
Stack: 
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Entities$CoreCharset.ordinal()" because "charset" is null
at org.jsoup@1.15.3/org.jsoup.nodes.Entities.canEncode(Entities.java:298)
at org.jsoup@1.15.3/org.jsoup.nodes.Entities.escape(Entities.java:239)
at org.jsoup@1.15.3/org.jsoup.nodes.Entities.escape(Entities.java:145)
```
=> Fix NPE in escaping if output settings cloned twice

CHANGES, src/main/java/org/jsoup/helper/W3CDom.java, src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/main/java/org/jsoup/parser/Parser.java, src/main/java/org/jsoup/parser/Tag.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/main/java/org/jsoup/parser/XmlTreeBuilder.java, src/main/java/org/jsoup/safety/Cleaner.java, src/main/java/org/jsoup/select/Evaluator.java, src/test/java/org/jsoup/parser/HtmlParserTest.java, src/test/java/org/jsoup/parser/HtmlTreeBuilderStateTest.java, src/test/java/org/jsoup/parser/HtmlTreeBuilderTest.java, src/test/java/org/jsoup/parser/TagTest.java, src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java
Includes namespace support in tags.
Includes support for preserving the case of tags and attributes in the SVG or MathML namespaces.
=> Added support for svg and math foreign elements

CHANGES, pom.xml, src/main/java/org/jsoup/select/Elements.java, src/test/java/org/jsoup/select/ElementsTest.java
Improvement: in the Elements list, added direct support for:
- `#set(index, element)`, 
- `#remove(index)`,
- `#remove(object)`,
- `#clear()`,
- `#removeAll(collection)`,
- `#retainAll(collection)`,
- `#removeIf(filter)`,
- `#replaceAll(operator)`.
These methods update the original DOM, as well as the Elements list.
=> Extend Elements to update the backing DOM on set(), remove(), et al

.github/workflows/build.yml, CHANGES, pom.xml, src/main/java9/module-info.java
Adds an explicit `module-info.java` file. As a native module, tools requiring modules such as jlink will operate correctly without warnings.
This makes jsoup a multi-release jar so it's still compatible with java 8. The `module-info.java` file is:
```java
module org.jsoup {
exports org.jsoup;
exports org.jsoup.helper;
exports org.jsoup.nodes;
exports org.jsoup.parser;
exports org.jsoup.safety;
exports org.jsoup.select;
requires transitive java.xml; // for org.w3c.dom out of W3CDom
}
```
**Nullability annotations**
I looked at having also a `requires static jsr305` entry as well. That's a build time dependency for our javax nonnull annotations. However as that's an automodule, we get the compile warning `Required filename-based automodules detected: [jsr305-3.0.2.jar]. Please don't publish …
=> Repackaged the library with native (vs automatic) JPMS module support

.github/workflows/build.yml, pom.xml
Allows JDK8 to build, albeit without multi-release / modules. Allows the CI actions to test on Java 8.
Fixes #2026
=> Move the multi-release to a JDK9+ profile

CHANGES, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/ProxyTest.java, src/test/java/org/jsoup/integration/TestServer.java, src/test/java/org/jsoup/integration/servlets/BaseServlet.java, src/test/java/org/jsoup/integration/servlets/CookieServlet.java, src/test/java/org/jsoup/integration/servlets/DeflateServlet.java, src/test/java/org/jsoup/integration/servlets/EchoServlet.java, src/test/java/org/jsoup/integration/servlets/FileServlet.java, src/test/java/org/jsoup/integration/servlets/HelloServlet.java, src/test/java/org/jsoup/integration/servlets/InterruptedServlet.java, src/test/java/org/jsoup/integration/servlets/ProxyServlet.java, src/test/java/org/jsoup/integration/servlets/RedirectServlet.java, src/test/java/org/jsoup/integration/servlets/SlowRider.java
This adds a local test proxy implementation and some test cases for using Jsoup.connect.proxy().
=> Add a test proxy

CHANGES, pom.xml, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/AuthenticationHandler.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/helper/RequestAuthenticator.java, src/main/java9/org/jsoup/helper/RequestAuthHandler.java, src/test/java/org/jsoup/helper/AuthenticationHandlerTest.java, src/test/java/org/jsoup/helper/HttpConnectionTest.java, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/ProxyTest.java, src/test/java/org/jsoup/integration/TestServer.java, src/test/java/org/jsoup/integration/servlets/AuthFilter.java, src/test/java/org/jsoup/integration/servlets/ProxyServlet.java
Uses the multi-version support so that in Java versions that support it (9+), an authenticator is set via `java.net.HttpURLConnection.setAuthenticator()`.
On Java 8, we set the system-wide default authenticator, and use ThreadLocals to enable per-request authenticators.
Also adds tests for HTTP and HTTPS server and proxy basic authentication.
=> Added support for per-request authentication to Jsoup.connect

CHANGES, pom.xml, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/nodes/NodeIterator.java, src/main/java/org/jsoup/nodes/NodeUtils.java, src/main/java/org/jsoup/select/Collector.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/NodeTraversor.java, src/main/java/org/jsoup/select/StructuralEvaluator.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/nodes/NodeIteratorTest.java, src/test/java/org/jsoup/nodes/NodeStreamTest.java, src/test/java/org/jsoup/nodes/PositionTest.java, src/test/java/org/jsoup/select/TraversorTest.java
Improvement: added the NodeIterator class, to efficiently traverse a node tree using the Iterator interface.
And added Stream Element#stream() and Node#nodeStream() methods, to enable fluent composable stream pipelines of node traversals.
NodeIterator only hits nodes once (vs head and tail for NodeTraversor), is restartable, supports modifications of the node it just emitted (e.g. replace, remove), supports type filtering, and emits in document order.
Refactored most head-only uses of NodeTraversor to use the NodeIterator or a Stream backed by it.
=> Added NodeIterator and Stream support

CHANGES, src/main/java/org/jsoup/nodes/LeafNode.java, src/main/java/org/jsoup/nodes/Range.java, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/main/java/org/jsoup/parser/XmlTreeBuilder.java, src/test/java/org/jsoup/nodes/PositionTest.java
And Simplified and detangled the inserts in HtmlTreeBuilder and XmlTreeBuilder.
=> Improved accuracy of tracked source positions

CHANGES, src/main/java/org/jsoup/internal/SharedConstants.java, src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/nodes/Range.java, src/main/java/org/jsoup/parser/CharacterReader.java, src/main/java/org/jsoup/parser/ParseError.java, src/main/java/org/jsoup/parser/Parser.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/parser/Tokeniser.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/test/java/org/jsoup/nodes/PositionTest.java, src/test/java/org/jsoup/parser/CharacterReaderTest.java
=> Tracks the source range of attributes (name and value) when source tracking is on

CHANGES, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/ConstrainableInputStream.java, src/main/java/org/jsoup/internal/ControllableInputStream.java, src/main/java/org/jsoup/internal/SharedConstants.java, src/test/java/org/jsoup/integration/ConnectIT.java
To avoid pinning a virtual thread to a carrier thread, refactored ConstrainedInputStream into ControllableInputStream, which does not extend BufferedInputStream, but wraps it instead.
Had to provide a deprecation path in ConstrainedInputStream as changing the extends causes a binary backwards compatibility issue. Even though folks shouldn't be using Internal package classes, they may be.
Also enabled bodyStream to return a byte array stream after bufferUp(), in case constrains on the stream are still required.
This does not include a test case for pinning. Verified manually. Would be good to find a way to IT test it.
Fixes #2054
=> Avoid BufferedInputStream synchronized reads

src/main/java/org/jsoup/internal/SharedConstants.java, src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Range.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/main/java/org/jsoup/safety/Cleaner.java, src/test/java/org/jsoup/nodes/PositionTest.java, src/test/java/org/jsoup/safety/CleanerTest.java
And make sure attribute source ranges are copied in the cleaner
=> Refactored UserData to be tucked into a hash

CHANGES.md, pom.xml, src/main/java/org/jsoup/Jsoup.java, src/main/java/org/jsoup/helper/DataUtil.java, src/test/java/org/jsoup/helper/DataUtilTest.java, src/test/java/org/jsoup/integration/ParseTest.java
* Add Jsoup methods that accept a [`Path`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html).
* Also improve file parsing using [`SeekableByteChannel`](https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/channels/SeekableByteChannel.html) by resetting the current position after reading the magic bytes of the file being parsed.
=> Add Path-accepting Jsoup methods

src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/ControllableInputStream.java, src/main/java/org/jsoup/parser/CharacterReader.java, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/Parser.java, src/main/java/org/jsoup/parser/StreamParser.java, src/main/java/org/jsoup/parser/TreeBuilder.java, src/main/java/org/jsoup/parser/XmlTreeBuilder.java, src/test/java/org/jsoup/helper/DataUtilTest.java, src/test/java/org/jsoup/integration/ConnectIT.java, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/servlets/SlowRider.java, src/test/java/org/jsoup/parser/StreamParserTest.java
A **StreamParser** provides a progressive parse of its input. As each Element is completed, it is emitted via a Stream or Iterator interface. Elements returned will be complete with all their children, and an (empty) next sibling, if applicable.
Elements (or their children) may be removed from the DOM during the parse, for e.g. to conserve memory, providing a mechanism to parse an input document that would otherwise be too large to fit into memory, yet still providing a DOM interface to the document and its elements.
Additionally, the parser provides a `selectFirst(String query)` / `selectNext(String query)`, which will run the parser until a hit is found, at which point the parse is suspended. It can be resumed via another `select() `call, or via the `stream()` or `iterator()` methods. …
=> Progressive parsing with StreamParser

src/main/java/org/jsoup/helper/W3CDom.java, src/test/java/org/jsoup/helper/W3CDomTest.java
When we provide a custom output `Document` to `W3CDom#convert`, we receive a `NullPointerException` in the `W3CBuilder` constructor.
I've added a test that demonstrates the behavior. Here's the stacktrace from that test without the applied fix.
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.ownerDocument()" because "this.contextElement" is null
at org.jsoup.helper.W3CDom$W3CBuilder.<init>(W3CDom.java:364)
at org.jsoup.helper.W3CDom.convert(W3CDom.java:250)
at org.jsoup.helper.W3CDom.convert(W3CDom.java:238)
at org.jsoup.helper.W3CDomTest.canConvertToCustomDocument(W3CDomTest.java:199)
```
=> Fix NullPointerException in case a custom document is passed to W3CDom

src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/Progress.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/ControllableInputStream.java, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/SessionIT.java, src/test/java/org/jsoup/integration/servlets/FileServlet.java
This enables for e.g. a user interface to show download progress (in a TUI or GUI):
```java
Connection con = Jsoup.connect(url).onResponseProgress((processed, total, percent, response) -> {
log("Processed: " + processed + " of " + total + " (" + percent + "%)");
log("URL: " + response.url());
});
Document document = con.get();
```
It can also be set on a session level, and supports multi-threaded callers:
```java
Connection session = Jsoup.newSession()
.onResponseProgress((processed, total, percent, response) -> {
if (percent == 100.0f) {
log("Completed " + Thread.currentThread().getName() + "- " + response.url());
seenUrls.add(response.url().toExternalForm());
completedCount.incrementAndGet();
}
});
```
=> Added a Response progress event interface 

CHANGES.md, src/main/java/org/jsoup/parser/TreeBuilder.java, src/test/java/org/jsoup/parser/PositionTest.java, src/test/java/org/jsoup/parser/StreamParserTest.java, src/test/java/org/jsoup/safety/CleanerTest.java
This enables the source position tracking on the Document node (which was previously unset). Also enables the node traversor to see the outer Document node.
=> Emit onNodeInserted + onNodeClosed for the root document

CHANGES.md, src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Entities.java, src/main/java/org/jsoup/nodes/TextNode.java, src/main/java/org/jsoup/nodes/XmlDeclaration.java
Introduced an options bitset instead of all those boolean method options. Reduced cyclomatic complexity of from 29 to 14.
Improved throughput of escape around 22% if the content contains characters in supplemental plane, by no longer going through the charset encoder to test can encode, but pushing it into the CoreCharset. That removes a ByteBuffer allocation on each hit.
=> Simplified the Entities.escape method

pom.xml, src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/internal/ControllableInputStream.java, src/main/java/org/jsoup/internal/SharedConstants.java, src/main/java/org/jsoup/internal/SimpleBufferedInput.java, src/main/java/org/jsoup/internal/SoftPool.java, src/main/java/org/jsoup/internal/StringUtil.java, src/main/java/org/jsoup/parser/CharacterReader.java, src/test/java/org/jsoup/helper/DataUtilTest.java, src/test/java/org/jsoup/integration/ConnectIT.java, src/test/java/org/jsoup/integration/ConnectTest.java, src/test/java/org/jsoup/integration/ParseTest.java, src/test/java/org/jsoup/integration/servlets/EchoServlet.java, src/test/java/org/jsoup/integration/servlets/InterruptedServlet.java, src/test/java/org/jsoup/internal/SoftPoolTest.java, src/test/java/org/jsoup/parser/CharacterReaderTest.java, src/test/java/org/jsoup/parser/HtmlParserTest.java, src/test/java/org/jsoup/parser/TokeniserStateTest.java, src/test/java/org/jsoup/parser/TokeniserTest.java
The goal of BUFFMAN is to reduce memory consumption and reduce GC pressure within jsoup, through improved buffer management.
It picks up the thread from #1800 (by @chibenwa), which I got stalled on when reimplementing buffering in CharacterReader.
Specifically, the implementation will re-use `char[]` and `byte[]` arrays whenever possible, vs creating new ones on each read, which is the Java default pattern. And those buffers are able to be reaped by GC as the `SoftPool` implementation holds them in SoftReferences. That improves on the current implementation of this pattern in `StringUtil.borrowBuilder()`, which retains those for the lifecycle of the thread, which may be longer than the parser is required. The buffer sizes will also be lowered from the current defaults of 32K.
This initial …
=> Improve buffer management throughout the load/fetch and parse lifecycle

CHANGES.md, pom.xml
Android versions below 5.0 (API level 21) are obsolete these days. This change would allow the use of features such as `StandardCharsets`, which is available on Android 4.4 (API level 19) and higher.
This PR also changes one Sniffer dependency to [Gummy Bears](https://github.com/open-toast/gummy-bears), which has support for desugaring.
=> Bump minimum Android API level to 21

CHANGES.md, src/main/java/org/jsoup/Jsoup.java, src/main/java/org/jsoup/internal/SharedConstants.java, src/main/java/org/jsoup/safety/Cleaner.java, src/main/java/org/jsoup/safety/Safelist.java, src/test/java/org/jsoup/safety/CleanerTest.java
And allow relative links to be isValid.
Applies a dummy URI if one is not otherwise provided, to allow protocol resolution.
Fixes #1024
Fixes #643
=> In the Cleaner, don't add nofollow to relative links

CHANGES.md, pom.xml
Restructured the compile phases in the POM so that when executing on Java 9+, the base classes are compiled with `-release 8`. This ensures that the bootstrap class path uses the Java 8 API, and so the produced jar is binary compat with Java 8. 
(Whilst that option had been previously set, it was ignored as Maven's default compile stage was executed prior; this change disables the default compilations so that the platform specific activations are activated.)
When built on Java 8, the original `source` and `target` (vs `release`) are used.
Fixes an issue where when running on Java 8 (but built on Java9+),  `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;` would be thrown in ControllableInputStream buffering up, because the return expected `Buffer`, not the …
=> Enforce `-release` 8 base compilation target

CHANGES.md, src/main/java/org/jsoup/select/Elements.java, src/main/java/org/jsoup/select/Selector.java, src/test/java/org/jsoup/select/ElementsTest.java
Closes #2256.
I copied the docstrings, and behaviour, from the equivalent methods on `Element` and the surrounding methods on `Elements`.
=> Add `selectFirst` and `expectFirst` to Elements

CHANGES.md, src/main/java/org/jsoup/nodes/Comment.java, src/main/java/org/jsoup/nodes/XmlDeclaration.java, src/main/java/org/jsoup/parser/Token.java, src/main/java/org/jsoup/parser/Tokeniser.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/main/java/org/jsoup/parser/XmlTreeBuilder.java, src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java
Vs the old method of bouncing through the HTML parser's bogus comments.
This simplifies the parse flow for declarations and can better handle dodgy inputs.
=> Directly parse XML declarations in XmlTreeBuilder

CHANGES.md, src/main/java/org/jsoup/parser/HtmlTreeBuilder.java, src/main/java/org/jsoup/parser/HtmlTreeBuilderState.java, src/test/java/org/jsoup/parser/HtmlParserTest.java, src/test/resources/htmltests/adopt-1.html
Fixes #2267
The implementation of the adoption agency algorithm vs the HTML5 spec had drifted over time. This fixes that.
The spec for table fostering when in adoption is not presently implemented, marked as a todo.
Given the complexity of the algo and how it has changed over time, I opted to include it inline so that hopefully later changes are easier to _adopt_.
=> Reimplement the adoption agency algorithm

CHANGES.md, src/main/java/org/jsoup/nodes/Element.java, src/test/java/org/jsoup/nodes/ElementTest.java
Fixes #2282 
- Utilize id for not only the element itself, but also for its parent elements;
- Stop the processing when encountering an element with a unique id.
In case of an extremely deeply nested element, which is the reason for the changes in v1.16.2, this can possibly greatly reduce the size of the output of `cssSelector` if one of the element's parents has an id.
=> Restore the behavior of cssSelector before v1.16.2 for elements with an id

src/main/java/org/jsoup/parser/TokenQueue.java, src/test/java/org/jsoup/parser/TokenQueueTest.java, src/test/java/org/jsoup/select/SelectorTest.java
Rewrite `TokenQueue.consumeCssIdentifier()` to support escaped hex digits and to more closely match the relevant [CSS spec](https://www.w3.org/TR/css-syntax-3/#consume-name).
Part 1 of fixing #1967.
=> Change `TokenQueue.consumeCssIdentifier()` to support hex digit unescaping

src/main/java/org/jsoup/helper/ChangeNotifyingArrayList.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Node.java
We keep a lazy initialized, cached copy of an Element's child Element list, to save recreating it every time they are requested.
That was stored in a nullable field. This change moves it into the userdata section of the attributes instead.
Also, rather than tracking changes to the backing node list via a ChangeNotifyingArrayList, I'm using the ArrayList's modcount instead directly. So we can deprecate the ChangeNotifyingArrayList.
Ultimately this trims the shallow size of an Element from 40 to 32 bytes, and the NodeList from 32 to 24 (20% and 25% decreases respectively)
=> Store cached child els in Attributes, not field

src/main/java/org/jsoup/parser/TokenQueue.java, src/main/java/org/jsoup/select/Selector.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/parser/TokenQueueTest.java, src/test/java/org/jsoup/select/SelectorTest.java
Fixes #1984
Side note: This method seems useful to library users when programmatically building CSS selectors. I think it should be part of the stable API surface and not live inside of `TokenQueue`.
=> Use proper escaping in `TokenQueue.escapeCssIdentifier()`

src/main/java/org/jsoup/parser/TokenQueue.java, src/main/java/org/jsoup/select/CombiningEvaluator.java, src/main/java/org/jsoup/select/QueryParser.java, src/test/java/org/jsoup/select/QueryParserTest.java, src/test/java/org/jsoup/select/SelectorTest.java
The QueryParser, which parses CSS selectors, was growing unwieldy. This simplifies the implementation into a clearer recursive descent parser.
Particularly this removes some ugly precedence handling for the or `,` grouping, and redundant unescape / escape hops.
=> Revamp QueryParser

src/main/java/org/jsoup/select/QueryParser.java, src/test/java/org/jsoup/select/QueryParserTest.java
Rewrite grammar/parser to disallow consecutive combinators in CSS selectors while retaining the non-standard feature of starting a selector with a combinator.
=> Disallow consecutive combinators in CSS selectors

src/main/java/org/jsoup/internal/StringUtil.java, src/main/java/org/jsoup/parser/CharacterReader.java, src/main/java/org/jsoup/parser/TokenQueue.java, src/main/java/org/jsoup/parser/Tokeniser.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/test/java/org/jsoup/internal/StringUtilTest.java
Replace calls to `java.lang.Character.isLetter()` and `isDigit()`. In all these cases we really only want to allow ASCII letters or digits.
=> Only match ASCII letters and digits

src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/Node.java, src/test/java/org/jsoup/nodes/DocumentTest.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/parser/ParserIT.java
When cloning an Element or a Document, the same underlying Parser should be retained.
We were creating new Parsers with HTML treebuilders on each Element clone. Which is both heavyweight and incorrect.
The Parser is now threadsafe so if the cloned element was being used (appending HTML) across threads, this will still be safe. (Albeit not concurrent; users can set a new Parser via ownerDocument().parser().newInstance() for a copy if required.)
=> Retain same Parser in Document & Element clone

src/main/java/org/jsoup/nodes/Document.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/parser/Parser.java, src/test/java/org/jsoup/nodes/DocumentTest.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/parser/ParserIT.java
I've seen examples of people trying to use a Parser in a concurrent manner, and this may succeed in low-concurrency modes, but will fail when under pressure. Adding an explicit lock to ensure safety.
=> Make Parser instances threadsafe

pom.xml, src/main/java/org/jsoup/helper/DataUtil.java, src/main/java/org/jsoup/internal/SimpleBufferedInput.java, src/main/java/org/jsoup/internal/SimpleStreamReader.java
Continuing on the work in #2186 to reuse large buffers to minimize allocations (and therefore GC) during parsing, this change allows us to reuse the byte -> char decoding buffer.
Replaces uses of InputStreamReader with a simplified version, where we recycle the underlying byte buffer, vs creating a new 8k buffer on every parse.
Gives a good performance improvements for all but the largest inputs, where the allocation cost is amortized across a longer parse.
=> Add SimpleStreamReader

src/main/java/org/jsoup/internal/QuietAppendable.java, src/main/java/org/jsoup/nodes/Attribute.java, src/main/java/org/jsoup/nodes/Attributes.java, src/main/java/org/jsoup/nodes/CDataNode.java, src/main/java/org/jsoup/nodes/Comment.java, src/main/java/org/jsoup/nodes/DataNode.java, src/main/java/org/jsoup/nodes/DocumentType.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/Entities.java, src/main/java/org/jsoup/nodes/LeafNode.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/nodes/Printer.java, src/main/java/org/jsoup/nodes/PseudoTextElement.java, src/main/java/org/jsoup/nodes/TextNode.java, src/main/java/org/jsoup/nodes/XmlDeclaration.java, src/test/java/org/jsoup/SerializationExceptionTest.java, src/test/java/org/jsoup/internal/QuietAppendableTest.java, src/test/java/org/jsoup/nodes/DataNodeTest.java
The QuietAppender implements Appender, and rethrows any IOException as a runtime SerializationException.
This simplifies a bunch of throws and wraps that were otherwise scattered through the code.
As most cases of the appendable will be a StringBuilder, a specialized implementation just calls append without the try/catch.
=> Add QuietAppender

CHANGES.md, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/HttpConnection.java, src/main/java/org/jsoup/parser/CharacterReader.java, src/main/java/org/jsoup/parser/Parser.java, src/main/java/org/jsoup/parser/TokeniserState.java, src/test/java/org/jsoup/integration/ConnectIT.java, src/test/java/org/jsoup/integration/ConnectTest.java
For historical reasons (specifically that a response's body used to be fully buffered during `execute`), `Connection#body()` does not throw a checked IOException.
This change adds a new `Connection#readBody()` which does throw a checked exception, and a partner `Connection#readFully()` method to do the internal buffering.
Clarified relevant documentation.
=> Added IOException throwing `readFully` and `readBody`

CHANGES.md, src/main/java/org/jsoup/nodes/Entities.java, src/test/java/org/jsoup/nodes/AttributeTest.java, src/test/java/org/jsoup/nodes/DocumentTest.java, src/test/java/org/jsoup/nodes/EntitiesTest.java, src/test/java/org/jsoup/parser/XmlTreeBuilderTest.java
=> Escape `<` and `>` when serializing attribute values

CHANGES.md, pom.xml, src/main/java/org/jsoup/helper/Validate.java, src/main/java/org/jsoup/internal/Normalizer.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/nodes/LeafNode.java, src/main/java/org/jsoup/nodes/Node.java, src/main/java/org/jsoup/parser/StreamParser.java, src/main/java/org/jsoup/select/Collector.java, src/main/java/org/jsoup/select/CombiningEvaluator.java, src/main/java/org/jsoup/select/Elements.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/NodeEvaluator.java, src/main/java/org/jsoup/select/Nodes.java, src/main/java/org/jsoup/select/QueryParser.java, src/main/java/org/jsoup/select/Selector.java, src/main/java/org/jsoup/select/StructuralEvaluator.java, src/test/java/org/jsoup/helper/ValidateTest.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/nodes/NodeTest.java, src/test/java/org/jsoup/nodes/TextNodeTest.java, src/test/java/org/jsoup/select/EvaluatorDebug.java, src/test/java/org/jsoup/select/NodesTest.java, src/test/java/org/jsoup/select/QueryParserTest.java, src/test/java/org/jsoup/select/SelectorTest.java
This extends the QueryParser and Evaluators to support matching nodes (including specific node types, and their nodeValue contents)
Allows finding e.g. Elements following a particular comment or text node.
Also allows selecting nodes directly via 
- `Element#selectNodes(String css)` and 
- `Element#selectNodes(String css, Class nodeType)`
E.g.: `::comment:contains(prices) + p` will find `p` Elements directly after a `` comment.
Or: `div:has(>::comment)` will find `div` Elements that directly have comment children.
Available operators:
<table>
<tr><td colspan="3"><h3>Node pseudo selectors</h3></td></tr>
<tr><td colspan="3">These selectors enable matching specific leaf nodes, including Comments, TextNodes. When used with `Element#select(String)`, these can be used with structural selectors …
=> Selectors can match against Nodes

CHANGES.md, src/main/java/org/jsoup/Connection.java, src/main/java/org/jsoup/helper/RequestDispatch.java, src/main/java/org/jsoup/helper/UrlConnectionExecutor.java, src/main/java11/org/jsoup/helper/HttpClientExecutor.java, src/test/java/org/jsoup/integration/ConnectIT.java, src/test/java11/org/jsoup/helper/HttpClientExecutorTest.java
Change the default to prefer using the JDK's HttpClient over HttpUrlConnection, if available, to enable HTTP/2 support.
Users can disable via `-Djsoup.useHttpClient=false`.
=> Enable HTTP/2 by default if the HttpClient is available

CHANGES.md, src/main/java/org/jsoup/nodes/Printer.java, src/test/java/org/jsoup/nodes/NodeTest.java, src/test/java/org/jsoup/nodes/PrinterTest.java
Fixes #2347
I'm not sure if this can be fixed more elegantly than looping over sequential text nodes. I'd prefer handling multiple text nodes in a single call to `Entities.doEscape`, but that would involve larger code changes.
=> Collapse whitespace between adjacent TextNodes (#2347)

src/main/java/org/jsoup/helper/HttpConnection.java
Hi,
Previously, resources were generally closed in most cases, but there was an issue where resources were not properly closed when exceptions occurred.
In this PR, try-with-resources was applied to ensure that resources are always safely closed, even if an exception is thrown.
Thanks for reviewing!
=> Fix always close resources

CHANGES.md, src/main/java11/org/jsoup/helper/HttpClientExecutor.java, src/test/java11/org/jsoup/helper/HttpClientExecutorTest.java
@jhy 
Fixes #2388
HttpClient ignores system default proxy (`ProxySelector.getDefault()`).
select(): perRequestProxy → system ProxySelector → NoProxy
connectFailed() (One tiny opinion): 
Only forwards to system ProxySelector when it was actually used
Returns early for perRequestProxy (prevents incorrect failure reporting)
- All 1696 tests pass
- Added 2 unit tests for the new behavior
Thanks to @robseidel for reporting and suggesting the fix.
=> Fix: Use system default ProxySelector in HttpClient #2388

CHANGES.md, pom.xml, src/main/java/org/jsoup/helper/Re2jRegex.java, src/main/java/org/jsoup/helper/Regex.java, src/main/java/org/jsoup/internal/SharedConstants.java, src/main/java/org/jsoup/nodes/Element.java, src/main/java/org/jsoup/select/Evaluator.java, src/main/java/org/jsoup/select/NodeEvaluator.java, src/main/java/org/jsoup/select/QueryParser.java, src/test/java/org/jsoup/helper/RegexTest.java, src/test/java/org/jsoup/nodes/ElementTest.java, src/test/java/org/jsoup/select/EvaluatorTest.java
Added support for using the re2j regular expression engine for CSS selectors, which ensures linear-time performance for regex evaluation. This enables safe handling of arbitrary user-supplied query regexes. 
To enable, add the `com.google.re2j` dependency to your classpath, e.g.:
```xml
<dependency>
<groupId>com.google.re2j</groupId>
<artifactId>re2j</artifactId>
<version>1.8</version>
</dependency>
```
=> Added option to use re2j for CSS query regexes

CHANGES.md, src/main/java/org/jsoup/helper/UrlConnectionExecutor.java, src/main/java/org/jsoup/internal/Functions.java, src/main/java/org/jsoup/safety/Safelist.java
This was previously used to support older Android API levels without full `java.util.function` coverage; jsoup now requires core library desugaring so this indirection is no longer necessary.
=> Migrate away from internal Functions class
